### ISSUE TITLE
Cannot read property 'toRgb' of undefined when hsv() is called on rgba gradient

### ISSUE THREAD

**Issue by missbruni** [mistic100/tinygradient#36]
I am trying to get the HSV short interpolation for this two colors:
- rgba(86, 86, 86, 1)
- rgba(45, 163, 185, 1)

I run:
```
const gradient = tinygradient(['rgba(86, 86, 86, 1)','rgba(45, 163, 185, 1)']);
console.log(gradient.hsv(9, 'short'))
// Cannot read property 'toRgb' of undefined
```
This can be replicated on https://mistic100.github.io/tinygradient/, if you open the console and run the above. It seems work fine if I run 
```
console.log(gradient.rgb(9))
```
But I need the hsv interpolation on this case. 

Stack:

![image](https://user-images.githubusercontent.com/12257311/79439687-0b21a900-7fcd-11ea-8a61-9fc6c3796bfc.png)

**Comment by mistic100** [comment]
Fixed in 1.1.2, please note that HSV interpolation is not possible anyway when there is a grayscale color. The error was in the wallback from HSV to RGB.
