### ISSUE TITLE
Inaccuracies

### ISSUE THREAD

**Issue by brunnerh** [mistic100/tinygradient#38]
I noticed that sometimes different values yield the same color, so small jumps appear in what should be a smooth gradient.

e.g. blending from red to green in 255 steps:

```js
const gradient = tinygradient(['red', 'lime']);
for (let i = 0; i < 255; i++)
	console.log(gradient.rgbAt(i / 255).toRgb())
```

A part of the output showing the issue:

```js
{r: 8, g: 247, b: 0, a: 1}
{r: 8, g: 247, b: 0, a: 1}
{r: 5, g: 250, b: 0, a: 1}
{r: 5, g: 250, b: 0, a: 1}
{r: 5, g: 250, b: 0, a: 1}
{r: 3, g: 252, b: 0, a: 1}
{r: 3, g: 252, b: 0, a: 1}
```

Red values 6, 7 and 4 and green values 248, 249 and 251 are skipped, instead other values are repeated multiple times.
Multiple identical values can also be observed when converting to HSL, so i suspect the issue is the calculated underlying color.

**Comment by mistic100** [comment]
This is expected because the interpolation is done with integer precision. Tinygradient was never designed to generate smooth gradients.

**Comment by brunnerh** [comment]
That is unfortunate, is there any reason not to use higher precision though?

**Comment by mistic100** [comment]
No, it was just written like that at the time.
I don't think I will rewrite it but you can propose changes of it does not break anything.

**Comment by mistic100** [comment]
actually it seams it is a bug in the rgbAt and hsvAt methods, there is a useless Math.round

**Comment by mistic100** [comment]
If you use `gradient.rgb(255).map(c => c.toRgb())` instead of your loop it returns the correct values
