### ISSUE TITLE
Hello .. Thank you for a great library !!!

### ISSUE THREAD

**Issue by supertick** [mistic100/tinygradient#6]
Hello .. Thank you for a great library !!!

Just a small syntax error on the excellent examples ->  {h: 240: s: 1, v: 1, a: 1}, // HSVa object
The h: 240: <-- needs to be a comma not a colon.

Cheers !

var gradient = tinygradient([
  tinycolor('#ff0000'),       // tinycolor object
  {r: 0, g: 255, b: 0},       // RGB object
  {h: 240: s: 1, v: 1, a: 1}, // HSVa object  <------------- Here
  'rgb(120, 120, 0)',         // RGB CSS string
  'gold'                      // named color
]);

**Comment by mistic100** [comment]
thanks
