### ISSUE TITLE
Cannot resolve module 'tinycolor'

### ISSUE THREAD

**Issue by Sailias** [mistic100/tinygradient#7]
Why is tinygradient.js#9 use tinycolor2 and tinygradient.js#12 use tinycolor?

My issue is resolved when both are using tinycolor2.

**Comment by mistic100** [comment]
Bower component is named "tinycolor" https://github.com/bgrins/TinyColor/blob/master/bower.json
NPM component is named "tinycolor2" https://github.com/bgrins/TinyColor/blob/master/package.json (because "tinycolor" was already used)

If you run
``` 
$ bower search tinycolor
$ npm search tinycolor
```
 you can confirm it's not an error on tinygradient

**Comment by Sailias** [comment]
@mistic100 I am using webpack and with tinygradient installed via npm.
No bower

**Comment by mistic100** [comment]
Well there is not so much I can do... I won't rename the AMD import and break for everyone using bower.

You can ask bgrins to rename its bower package.

---
I don't know webpack but what about libs only available on bower ? you can't use them ?

**Comment by mistic100** [comment]
and if you use NPM why isn't the dependency resolved on line 9 via require ?

**Comment by Sailias** [comment]
because it's still inside a front-end application that uses webpack and not a nodejs server app, so module is not defined and the packages are installed with just plain npm.

I agree it's not your fault as they have named their modules different based on npm vs bower because tinycolor was already taken.

I am not sure if there is anything you can actually do.

**Comment by owap** [comment]
I encountered the same erorr, but I was able to get it working with webpack by installing `tinycolor2` via NPM, and `tinygradient` via bower.

**Comment by jonahkagan** [comment]
I was able to resolve this error by adding this to my webpack.config:

```js
resolve: {
    alias: {tinycolor: "tinycolor2"},
}
```

**Comment by KcYoung1997** [comment]
I understand that this is an old issue but i've been having the same problem. 

In my case as I'm not using bower the fix from @owap isn't applicable and as i'm using react-scripts I lack the ability to modify webpack.config like @Jonahkagan without a large amount of effort. 

Instead I added a local dependancy to my `package.json` to install tinycolor2 as tinycolor:
`"tinycolor": "file:./node_modules/tinycolor2",`
