### ISSUE TITLE
Gradient calculation

### ISSUE THREAD

**Issue by Triplecorpse** [mistic100/tinygradient#9]
Hi! Could you please implement a function that calculates gradient on specific position? Not step but smooth gradient.
For example, I created gradient with 2 steps: pos: 0 black and pos: 1 white, I want to calculate color on pos: 0.5 (it will be 50% grey or #777777).
I didn't met this functionality in any of gradient libs together with position setting
Looking forward to seeing your reply soon.

**Comment by mistic100** [comment]
Release 0.4.0
